#!/bin/bash
#SBATCH -J cutclass
#SBATCH --mail-type=END                      # Request status by email #SBATCH --partition=suh #SBATCH --constraint="gpu-mid|gpu-high" #SBATCH --exclude=fang-compute-01,fang-compute-02
#SBATCH --mail-user=ph448@cornell.edu        # Email address to send results to.#SBATCH --partition=suh #SBATCH --partition=suh  #SBATCH --exclude=rush-compute-03,dgx2-compute-02,davis-compute-02,brandal,abdelfattah-compute-02,lancer-compute-01,sun-compute-03,snavely-compute-03,seo-compute-01,seo-compute-02
#SBATCH -o ./slurm-%j.out                   #|a5500|3090 #SBATCH --nodelist=seo-compute-01 #SBATCH --partition=suh #SBATCH --constraint="[a6000|a100|h100]"
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --tasks-per-node=1
#SBATCH --get-user-env
#SBATCH --mem 300G
#SBATCH -t 24:00:00
#SBATCH --gres=gpu:2
#SBATCH --requeue
#SBATCH --partition=suh 
export CUDA_VISIBLE_DEVICES=0,1 #,2,3
export WORLD_SIZE=4
source /home/ph448/.bashrc
conda activate sigma
echo $SLURMD_NODENAME

# cd /share/suh-scrap2/ph448/cutlass/build
mkdir /share/suh-scrap2/ph448/test/EzPC/tmp
export TMPDIR=/share/suh-scrap2/ph448/test/EzPC/tmp
export CUDA_HOME=$CONDA_PREFIX
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export NVCC_PATH="/share/suh-scrap2/ph448/envs/sigma/bin/nvcc"
# make -j$(nproc)
# /share/suh-scrap2/ph448/cutlass/tools/test/unit/cutlass_test
# make test_unit -j
export CUDA_VERSION=11.7
export GPU_ARCH=86

cd /share/suh-scrap2/ph448/test/EzPC/GPU-MPC



# make clean
# echo "Building CUTLASS"
# # Build CUTLASS
# cd ext/cutlass;
# # make clean
# if [ -n "$1" ]
# then 
# git checkout main;
# fi
# mkdir build
# cd build
# cmake .. \
#   -DCUTLASS_NVCC_ARCHS=$GPU_ARCH \
#   -DCMAKE_CUDA_COMPILER=$NVCC_PATH \
#   -DCUDAToolkit_ROOT="$CONDA_PREFIX" \
#   -DCMAKE_CUDA_FLAGS="-I$CONDA_PREFIX/include -L$CONDA_PREFIX/lib" \
#   -DCMAKE_CXX_FLAGS="-I$CONDA_PREFIX/include"
# make -j$(8);
# cd ../../..;

# Build sytorch
# echo "Building Sytorch"
# cd ext/sytorch;
# mkdir build && cd build;
# cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release ../ -DCUDAToolkit_ROOT=$CUDA_HOME;
# make sytorch -j$(8);
# cd ../../..;

# # Download CIFAR-10
# cd experiments/orca/datasets/cifar-10;
# sh download-cifar10.sh;
# cd ../../../..;


# # Make shares of data
# make share_data;
# cd experiments/orca;
# ./share_data;
# cd ../..;

# Build the orca codebase
# make orca; 

# Make output directories
# Orca
# mkdir experiments/orca/output;
# mkdir experiments/orca/output/P0;
# mkdir experiments/orca/output/P1;
# mkdir experiments/orca/output/P0/training;
# mkdir experiments/orca/output/P1/training;
# mkdir experiments/orca/output/P0/inference;
# mkdir experiments/orca/output/P1/inference;

# # Sigma
# mkdir experiments/sigma/output;
# mkdir experiments/sigma/output/P0;
# mkdir experiments/sigma/output/P1;

# # sh setup.sh main
make orca -j4;
# conda install matplotlib
cd experiments/orca;

python run_experiment.py --table 9 --party 0 &
python run_experiment.py --table 9 --party 1